export const courses = [
    {
        courseId: 1,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-one.svg",
        plays: 20,
    },
    {
        courseId: 2,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-two.svg",
        plays: 20,
    },
    {
        courseId: 3,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-three.svg",
        plays: 20,
    },
    {
        courseId: 4,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-four.svg",
        plays: 20,
    },
    {
        courseId: 5,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-five.svg",
        plays: 20,
    },
    {
        courseId: 6,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-six.svg",
        plays: 20,
    },
    {
        courseId: 7,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-one.svg",
        plays: 20,
    },
    {
        courseId: 8,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-two.svg",
        plays: 20,
    },
    {
        courseId: 9,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-three.svg",
        plays: 20,
    },
    {
        courseId: 10,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-four.svg",
        plays: 20,
    },
    {
        courseId: 11,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-five.svg",
        plays: 20,
    },
    {
        courseId: 12,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-six.svg",
        plays: 20,
    },
    {
        courseId: 13,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-one.svg",
        plays: 20,
    },
    {
        courseId: 14,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-two.svg",
        plays: 20,
    },
    {
        courseId: 15,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-three.svg",
        plays: 20,
    },
    {
        courseId: 16,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-four.svg",
        plays: 20,
    },
    {
        courseId: 17,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-five.svg",
        plays: 20,
    },
    {
        courseId: 18,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-six.svg",
        plays: 20,
    },
    {
        courseId: 19,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-one.svg",
        plays: 20,
    },
    {
        courseId: 20,
        title: "Web Design basic to advanced",
        price: 560,
        rating: 4.8,
        students: 413,
        image: "/assets/image/courses/rectangle-two.svg",
        plays: 20,
    },
];

export const categories = [
    { name: 'HTML & CSS', count: 5, id: 1 },
    { name: 'UX/UI Design', count: 5, id: 2 },
    { name: 'Web Development', count: 5, id: 3 },
    { name: 'Python', count: 5, id: 4 },
    { name: 'HTML & CSS', count: 5, id: 5 },
    { name: 'UX/UI Design', count: 5, id: 6 },
    { name: 'Web Development', count: 5, id: 7 },
    { name: 'Python', count: 5, id: 8 },
]

export const upcomingCourses = [
    {
        id: 1,
        title: "Colors Theory For Designers",
        instructor: "John Doe",
        lessonCount: 0,
        duration: "00:00:00",
        price: '0',
        imageUrl: "/assets/image/courses/upcoming-courses-1.svg",
        instructorAvatarUrl: "/assets/image/courses/avatar-one.svg",
    },
    {
        id: 2,
        title: "Colors Theory For Designers",
        instructor: "John Doe",
        lessonCount: 0,
        duration: "00:00:00",
        price: '0',
        imageUrl: "/assets/image/courses/upcoming-courses-2.svg",
        instructorAvatarUrl: "/assets/image/courses/avatar-two.svg",
    },
    {
        id: 3,
        title: "Colors Theory For Designers",
        instructor: "John Doe",
        lessonCount: 0,
        duration: "00:00:00",
        price: '0',
        imageUrl: "/assets/image/courses/upcoming-courses-3.svg",
        instructorAvatarUrl: "/assets/image/courses/avatar-three.svg",
    },
    {
        id: 4,
        title: "Colors Theory For Designers",
        instructor: "John Doe",
        lessonCount: 0,
        duration: "00:00:00",
        price: '0',
        imageUrl: "/assets/image/courses/upcoming-courses-4.svg",
        instructorAvatarUrl: "/assets/image/courses/avatar-four.svg",
    },
];

export const stats = [
    { number: "15K+", label: "Students" },
    { number: "35", label: "Main questions" },
    { number: "75%", label: "Total success" },
    { number: "16", label: "Years of experience" },
    { number: "26", label: "Chief experts" },
];

export const topInstructors = [
    {
        imageUrl: '/assets/image/courses/instructor-one.svg',
        facebookUrl: 'https://www.facebook.com/',
        twitterUrl: 'https://twitter.com/',
        instagramUrl: 'https://www.instagram.com/',
        name: 'John Doe',
    },
    {
        imageUrl: '/assets/image/courses/instructor-two.svg',
        facebookUrl: 'https://www.facebook.com/',
        twitterUrl: 'https://twitter.com/',
        instagramUrl: 'https://www.instagram.com/',
        name: 'John Doe',
    },
    {
        imageUrl: '/assets/image/courses/instructor-three.svg',
        facebookUrl: 'https://www.facebook.com/',
        twitterUrl: 'https://twitter.com/',
        instagramUrl: 'https://www.instagram.com/',
        name: 'John Doe',
    }
]